baseURL = "www.brookshelley.com"
languageCode = "en-us"
title = "dill & fennel"

[params]
	mainSections = ["posts"]
  subtitle = "a blog"
	favicon = "/favicon.ico"
	logo = "/666.png"

[outputs]
  home = ["HTML", "RSS"]
