baseURL = "https://www.brookshelley.com/"
languageCode = "en-us"
title = "dill & fennel"
theme = "brook"

copyright = "© Brook Shelley 2022"

# Enable syntax highlighting.
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 10
summaryLength = 20
ignoreErrors = ["error-remote-getjson"]

[params]
	mainSections = ["posts"]
	disableDisqusTypes = ["page", "posts"]
	disableDateTypes = ["page"]
  featherIconsCDN = true
  subtitle = "a blog"
	favicon = "/favicon.ico"
	logo = "/666.png"
	mode = "light" # "dark", "auto", "light"

	[[params.social]]
	name = "RSS"
	icon = "rss"
	url = "/index.xml"

	[[params.social]]
	name = "Github"
	icon = "github"
	url = "https://github.com/brookshelley"
	
	[[params.social]]
	name = "Letterboxd"
	url = "https://www.letterboxd.com/brookshelley"

	[[params.social]]
	name = "Twitter"
	icon = "twitter"
	url = "https://twitter.com/brookshelley"

	[[params.social]]
  name = "newsletter"
  icon = "mail"
  url = "/tags/newsletter"

  [[params.social]]
  name = "about"
  icon = "info"
  url = "/about"

[minify]
  disableCSS = false
  disableHTML = false
  disableJSON = false
  disableSVG = false
  minifyOutput = false
  
[caches]
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = -1
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = -1

[menu]

  [[menu.footer]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "read"
    url = "/books"
    weight = 1

  [[menu.main]]
    name = "seen"
    url = "/movies"
    weight = 2

  [[menu.main]]
    name = "about"
    url = "/about"
    weight = 3

[outputs]
	home = ["HTML", "RSS"]
