[build]
publish = "public"
command = "hugo --gc --minify"
ignoreErrors = ["error-remote-getjson"]

[build.processing]
  skip_processing = true
  
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  # Set minimum thresholds for each report area
  [plugins.inputs.thresholds]
    performance = 0.9
  
  # to audit a specific absolute url
  [[plugins.inputs.audits]]
    url = "https://brookshelley.com"
  
    # you can specify thresholds per audit
    [plugins.inputs.audits.thresholds]
      performance = 0.9

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[context.production.environment]
HUGO_VERSION = "0.118.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.118.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.118.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.118.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
